name: mobileinpact
description: An unofficial client for NextInpact

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  wakelock: ^0.6.2
  sqflite: ^2.2.3
  http: ^0.13.5
  webfeed: ^0.7.0
  flutter_html: ^2.2.1
  flutter_launcher_icons: ^0.11.0
  shared_preferences: ^2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/nxix-favicon.png'